name: Publish to Registry
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Set env variables
        run: |
          echo "::set-env name=CURRENT_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo "::set-env name=IMAGE_VERSION::${GITHUB_REF##*/}"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          build_args: BUILD_DATE=${{ env.CURRENT_DATE }},VERSION=${{ env.IMAGE_VERSION }},GAUGE_VERSION=${{ env.IMAGE_VERSION }},VCS_REF=${{ env.GITHUB_REF }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: jdk11/Dockerfile
          repository: sitture/docker-gauge-java/docker-gauge-java
          tag_with_ref: true
          tags: latest